name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests and build
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Copy .env.testing
        run: php -r "file_exists('.env.testing') || copy('.env.testing.example', '.env.testing');"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Generate Laravel Passport keys
        run: php artisan passport:keys

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Prepare SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run test suite
        run: php artisan icons:cache && php artisan test --parallel

  deploy:
    name: Deploy to target host
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ~/www/staging/artisan down
            cd ~/www/staging && git pull && composer install --no-interaction --optimize-autoloader && composer dump-autoload && php artisan migrate --force && php artisan optimize:clear
            sudo supervisorctl restart all
            ~/www/staging/artisan up
            exit
